const EXIT_CODES = Object.freeze({
  SUCCESS: 0,
  UNEXPECTED_RUNTIME_ERROR: 1,
  USAGE_PARSER_ERROR: 2,
  CONFIG_SCHEMA_ERROR: 3,
  SOURCE_GIT_NETWORK_ERROR: 4,
  POLICY_FAIL_STOP: 5,
  USER_REJECTED_PLAN: 6,
  SCOPE_SAFETY_VIOLATION: 7,
  DEPENDENCY_INSTALL_ERROR: 8,
  VERIFY_DIFF_MISMATCH: 9,
});

const REPORT_SCHEMA_VERSION = "qui-report/v1";
const CONFIG_SCHEMA_VERSION = "qui-config/v1";
const DEFAULT_TARGET_PATH = "src/components/ui";

module.exports = {
  CONFIG_SCHEMA_VERSION,
  DEFAULT_TARGET_PATH,
  EXIT_CODES,
  REPORT_SCHEMA_VERSION,
};
